### ISSUE TITLE
GUI drawing discussion

### ISSUE THREAD

**Issue by MasterDomino** [Ciapa/OpenTale#3]
MahApps.Metro provides variety of different customization options for GUI with MVVM pattern its more performant than basic VS Form builder, uses WPF.

**Comment by Ciapa1** [comment]
Problem with WPF is missing Cross Compatibility. For now, it is best to stay with Forms, even if less performant and somewhat hacky. If we switch to WPF(my first Idea was to go with WPF), the Program fails to launch in Linux and OSX due to missing compatibility.

**Comment by MasterDomino** [comment]
other way would be to use some API's like Vulcan, OpenGL, IDK. but maybe we could take a look at that: https://github.com/ronnycsharp/WPFLight, because WinForms are also not cross-platform

**Comment by Ciapa** [comment]
Too much effort for now. This is for now just doing basic implementations. And WinForms at least runs on Linux/OSX, whereas WPF doesn't even bother to run. So, until the real GUI with 3D rendering is coming, WinForms should be sufficient, as it's only to test how to implement stuff the best way and to implement it at all.

**Comment by MasterDomino** [comment]
should we leave this issue open then for future purposes?

**Comment by Ciapa** [comment]
It should be closed for now since it is not releated to the current milestone in any way
